name: Check binary size

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled, ready_for_review]

jobs:
  check_size:
    runs-on: ubuntu-latest
    # Check if pull request does not have label "bloat-ok".
    if: "!contains(github.event.pull_request.labels.*.name, 'bloat-ok')"
    steps:
    - uses: actions/checkout@v3
      with:
        # Checkout the base branch to set the baseline binary size
        ref: ${{ github.base_ref }}
    - name: Configure git user details
      run: |
        git config --global user.email "checkpoint-restore@users.noreply.github.com"
        git config --global user.name "checkpoint-restore"
    - name: Store baseline binary size
      # The first run of the script will store the size of the binary
      run: test/check-size.sh
    - name: Compare binary size change across each commit
      run: |
        git fetch origin ${{ github.head_ref }}
        git switch ${{ github.head_ref }}
        git rebase ${{ github.base_ref }} -x test/check-size.sh
